python:
  - "2.7"
script:
  - mkdir BUILD
# Assert that the Doxygen build produced no warnings.
# The strange command below asserts that the Doxygen command had an
# output of zero length
  - |
    doxygen doxyfile_options 2>&1 | tee BUILD/doxygen.out && [ ! -s BUILD/doxygen.out ]
# Assert that all binary libraries are named correctly
# The strange command below asserts that there are exactly 0 libraries that do
# not start with lib
  - |
    find "(" -name "*.a" -or -name "*.ar" ")" -and -not -name "lib*" | tee BUILD/badlibs | sed -e "s/^/Bad library name found: /" && [ ! -s BUILD/badlibs ]
# Assert that all assebler files are named correctly
# The strange command below asserts that there are exactly 0 libraries that do
# end with .s
  - |
    find  -name "*.s" | tee BUILD/badasm | sed -e "s/^/Bad Assembler file name found: /" && [ ! -s BUILD/badasm ]
  - make -C events/equeue test clean
  - PYTHONPATH=. coverage run -a -m pytest tools/test
  - python2 tools/test/pylint.py
  - coverage run -a tools/project.py -S
  - python2 tools/build_travis.py
  - coverage html
after_success:
  - coveralls
before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo add-apt-repository -y ppa:libreoffice/libreoffice-4-2
  - sudo apt-get update -qq
  - sudo apt-get install -qq gcc-arm-embedded doxygen --force-yes
  # Print versions we use
  - arm-none-eabi-gcc --version
  - python --version
  - doxygen --version
install:
  - pip install --user -r requirements.txt
  - pip install --user pytest
  - pip install --user pylint
  - pip install --user hypothesis
  - pip install --user mock
  - pip install --user coverage
  - pip install --user coveralls
